### ISSUE TITLE
Add an error message when a search does not return any results

### ISSUE THREAD

**Issue by joelzehring** [zuk881/blue_barracudas#35]

**Comment by phil4lif** [comment]
@sharkrachel is working on something, so that the display tables are hidden until the results come back then the display tables are shown with the results.  She can maybe include another modal in this to say something like "no results, please try different search criteria"  Since she knows how to do modals now.

**Comment by sharkrachel** [comment]
Closing this out so it doesn't pop up on my homepage. :)
